- name: ansible
  skus:
    MCT3691:
        is_trial: false
    MCT3691RN:
        is_trial: false
    MCT3691F3:
        is_trial: false
    MCT3691F3RN:
        is_trial: false
    MCT3691S:
        is_trial: false
    MCT3692:
        is_trial: false
    MCT3692RN:
        is_trial: false
    MCT3692F3:
        is_trial: false
    MCT3692F3RN:
        is_trial: false
    MCT3692S:
        is_trial: false
    MCT3693:
        is_trial: false
    MCT3693RN:
        is_trial: false
    MCT3693F3:
        is_trial: false
    MCT3693F3RN:
        is_trial: false
    MCT3693S:
        is_trial: false
    MCT3694:
        is_trial: false
    MCT3694RN:
        is_trial: false
    MCT3694F3:
        is_trial: false
    MCT3694F3RN:
        is_trial: false
    MCT3694S:
        is_trial: false
    MCT3695:
        is_trial: false
    MCT3695RN:
        is_trial: false
    MCT3695F3:
        is_trial: false
    MCT3695F3RN:
        is_trial: false
    MCT3695S:
        is_trial: false
    MCT3696:
        is_trial: false
    MCT3696RN:
        is_trial: false
    MCT3696F3:
        is_trial: false
    MCT3696F3RN:
        is_trial: false
    MCT3696S:
        is_trial: false
    MCT3733:
        is_trial: false
    MCT3733RN:
        is_trial: false
    MCT3733F3:
        is_trial: false
    MCT3733F3RN:
        is_trial: false
    MCT3733S:
        is_trial: false
    MCT3319:
        is_trial: false
    MCT3319F3:
        is_trial: false
    MCT3319RN:
        is_trial: false
    MCT3319S:
        is_trial: false
    MCT3320:
        is_trial: false
    MCT3320F3:
        is_trial: false
    MCT3320RN:
        is_trial: false
    MCT3320S:
        is_trial: false
    MCT3321:
        is_trial: false
    MCT3321F3:
        is_trial: false
    MCT3321RN:
        is_trial: false
    MCT3321S:
        is_trial: false
    MCT3742:
        is_trial: false
    MCT3742F3:
        is_trial: false
    MCT3742RN:
        is_trial: false
    MCT3742S:
        is_trial: false
    MCT3743:
        is_trial: false
    MCT3743F3:
        is_trial: false
    MCT3743RN:
        is_trial: false
    MCT3743S:
        is_trial: false
    MCT3744:
        is_trial: false
    MCT3744F3:
        is_trial: false
    MCT3744RN:
        is_trial: false
    MCT3744S:
        is_trial: false
    MCT3685:
        is_trial: false
    MCT3685RN:
        is_trial: false
    MCT3685F3:
        is_trial: false
    MCT3685F3RN:
        is_trial: false
    MCT3685S:
        is_trial: false
    SER0496:
        is_trial: true
    SER0496RN:
        is_trial: true
    SER0496F3:
        is_trial: true
    SER0496F3RN:
        is_trial: true
    SER0496S:
        is_trial: true
    SER0497:
        is_trial: true
    SER0497RN:
        is_trial: true
    SER0497F3:
        is_trial: true
    SER0497F3RN:
        is_trial: true
    SER0497S:
        is_trial: true
    SER0569:
        is_trial: true
    SER0569RN:
        is_trial: true
    SER0569F3:
        is_trial: true
    SER0569F3RN:
        is_trial: true
    SER0569S:
        is_trial: true
    SER0574:
        is_trial: true

- name: cost_management
  skus:
    MW00454:
        is_trial: false
    MW00455:
        is_trial: false
    MW00456:
        is_trial: false
    MW00457:
        is_trial: false
    MW00458:
        is_trial: false
    MW00459:
        is_trial: false
    MW00448:
        is_trial: false
    MW00449:
        is_trial: false
    MW00450:
        is_trial: false
    MW00451:
        is_trial: false
    MW00452:
        is_trial: false
    MW00453:
        is_trial: false
    MW00373:
        is_trial: false
    MW00374:
        is_trial: false
    MW00375:
        is_trial: false
    MW00376:
        is_trial: false
    MW00377:
        is_trial: false
    MW00378:
        is_trial: false
    MW00361:
        is_trial: false
    MW00362:
        is_trial: false
    MW00363:
        is_trial: false
    MW00364:
        is_trial: false
    MW00365:
        is_trial: false
    MW00366:
        is_trial: false
    MCT2735:
        is_trial: false
    MCT2736:
        is_trial: false
    MCT3489:
        is_trial: false
    MCT3490:
        is_trial: false
    MCT3753:
        is_trial: false
    MCT3754:
        is_trial: false
    MCT3759:
        is_trial: false
    MCT3760:
        is_trial: false
    MW00329:
        is_trial: false
    MW00330:
        is_trial: false
    MW00330F3:
        is_trial: false
    MW00331:
        is_trial: false
    MW00332:
        is_trial: false
    MW00421:
        is_trial: false
    MW00422:
        is_trial: false
    MCT2862:
        is_trial: false
    MCT2863:
        is_trial: false

- name: insights
  use_valid_acc_num: true

- name: migrations
  use_valid_acc_num: true

- name: subscriptions
  use_valid_acc_num: true

- name: settings
  use_valid_acc_num: true

- name: openshift
  use_valid_acc_num: false

- name: smart_management
  skus:
    SVC3124:
        is_trial: false
    RH00066:
        is_trial: false
    RH00065:
        is_trial: false
